# 権限の設定
sudo: required

# Dockerを使う
services: docker

# コンテナを起動
# ログインするときのパスワードとして環境変数を使う
before_install:
  - docker-compose up --build -d
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

# DBを準備
script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test

# Heroku特有の書き方
deploy:
  provider: script
  script:
    # Dockerfile.prod　をタグ付けしながらbuild
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    # HerokuのDockerレジストリにpush
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    # コンテナを立てる際に、db:migrateを実行しておく
    heroku run --app $HEROKU_APP_NAME rails db:migrate;
  # masterにマージされたときだけdeployする
  on:
    branch: master